-- Historial de cambios para equipos (incluye luces de emergencia)

CREATE TABLE IF NOT EXISTS public.equipos_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id uuid NOT NULL REFERENCES public.equipos(id),
  version integer NOT NULL,
  accion text NOT NULL CHECK (
    accion IN ('INSERT', 'UPDATE', 'SOFT_DELETE', 'RESTORE')
  ),
  changed_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  changed_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  old_data jsonb,
  new_data jsonb,
  changed_fields text[] NOT NULL DEFAULT '{}'::text[],
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

WITH duplicated_versions AS (
  SELECT
    id,
    row_number() OVER (
      PARTITION BY equipo_id, version
      ORDER BY id DESC
    ) AS row_num
  FROM public.equipos_historial
)
DELETE FROM public.equipos_historial history
USING duplicated_versions dup
WHERE history.id = dup.id
  AND dup.row_num > 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_equipos_historial_equipo_version
  ON public.equipos_historial (equipo_id, version);

CREATE INDEX IF NOT EXISTS idx_equipos_historial_equipo_changed_at
  ON public.equipos_historial (equipo_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_equipos_historial_changed_by
  ON public.equipos_historial (changed_by)
  WHERE changed_by IS NOT NULL;

CREATE OR REPLACE FUNCTION public.log_equipo_historial()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  changed_fields text[] := '{}'::text[];
  action_name text;
  next_version integer;
BEGIN
  IF TG_OP = 'INSERT' THEN
    action_name := 'INSERT';
    changed_fields := ARRAY[
      'id_property',
      'id_equipamento',
      'codigo',
      'ubicacion',
      'detalle_ubicacion',
      'estatus',
      'config',
      'equipment_detail'
    ];
  ELSIF TG_OP = 'UPDATE' THEN
    IF NEW.id_property IS DISTINCT FROM OLD.id_property THEN
      changed_fields := array_append(changed_fields, 'id_property');
    END IF;

    IF NEW.id_equipamento IS DISTINCT FROM OLD.id_equipamento THEN
      changed_fields := array_append(changed_fields, 'id_equipamento');
    END IF;

    IF NEW.codigo IS DISTINCT FROM OLD.codigo THEN
      changed_fields := array_append(changed_fields, 'codigo');
    END IF;

    IF NEW.ubicacion IS DISTINCT FROM OLD.ubicacion THEN
      changed_fields := array_append(changed_fields, 'ubicacion');
    END IF;

    IF NEW.detalle_ubicacion IS DISTINCT FROM OLD.detalle_ubicacion THEN
      changed_fields := array_append(changed_fields, 'detalle_ubicacion');
    END IF;

    IF NEW.estatus IS DISTINCT FROM OLD.estatus THEN
      changed_fields := array_append(changed_fields, 'estatus');
    END IF;

    IF NEW.config IS DISTINCT FROM OLD.config THEN
      changed_fields := array_append(changed_fields, 'config');
    END IF;

    IF NEW.equipment_detail IS DISTINCT FROM OLD.equipment_detail THEN
      changed_fields := array_append(changed_fields, 'equipment_detail');
    END IF;

    IF coalesce(array_length(changed_fields, 1), 0) = 0 THEN
      RETURN NEW;
    END IF;

    IF coalesce(OLD.estatus, '') <> 'INACTIVO'
      AND coalesce(NEW.estatus, '') = 'INACTIVO' THEN
      action_name := 'SOFT_DELETE';
    ELSIF coalesce(OLD.estatus, '') = 'INACTIVO'
      AND coalesce(NEW.estatus, '') <> 'INACTIVO' THEN
      action_name := 'RESTORE';
    ELSE
      action_name := 'UPDATE';
    END IF;
  ELSE
    RETURN NEW;
  END IF;

  SELECT coalesce(MAX(version), 0) + 1
  INTO next_version
  FROM public.equipos_historial
  WHERE equipo_id = NEW.id;

  INSERT INTO public.equipos_historial (
    equipo_id,
    version,
    accion,
    changed_at,
    changed_by,
    old_data,
    new_data,
    changed_fields
  )
  VALUES (
    NEW.id,
    next_version,
    action_name,
    timezone('utc', now()),
    coalesce(NEW.updated_by, NEW.created_by, auth.uid()),
    CASE
      WHEN TG_OP = 'UPDATE' THEN
        jsonb_strip_nulls(
          jsonb_build_object(
            'id_property', OLD.id_property,
            'id_equipamento', OLD.id_equipamento,
            'codigo', OLD.codigo,
            'ubicacion', OLD.ubicacion,
            'detalle_ubicacion', OLD.detalle_ubicacion,
            'estatus', OLD.estatus,
            'config', OLD.config,
            'equipment_detail', OLD.equipment_detail
          )
        )
      ELSE NULL
    END,
    jsonb_strip_nulls(
      jsonb_build_object(
        'id_property', NEW.id_property,
        'id_equipamento', NEW.id_equipamento,
        'codigo', NEW.codigo,
        'ubicacion', NEW.ubicacion,
        'detalle_ubicacion', NEW.detalle_ubicacion,
        'estatus', NEW.estatus,
        'config', NEW.config,
        'equipment_detail', NEW.equipment_detail
      )
    ),
    changed_fields
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_equipo_historial ON public.equipos;

CREATE TRIGGER trg_log_equipo_historial
AFTER INSERT OR UPDATE ON public.equipos
FOR EACH ROW
EXECUTE FUNCTION public.log_equipo_historial();

ALTER TABLE public.equipos_historial ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS authenticated_select ON public.equipos_historial;
CREATE POLICY authenticated_select
ON public.equipos_historial
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS authenticated_insert ON public.equipos_historial;
CREATE POLICY authenticated_insert
ON public.equipos_historial
FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS authenticated_update ON public.equipos_historial;
CREATE POLICY authenticated_update
ON public.equipos_historial
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.equipos_historial TO authenticated;

DO $$
BEGIN
  IF to_regclass('public.equipos_historial_id_seq') IS NOT NULL THEN
    GRANT USAGE, SELECT ON SEQUENCE public.equipos_historial_id_seq TO authenticated;
  END IF;
END;
$$;

INSERT INTO public.equipos_historial (
  equipo_id,
  version,
  accion,
  changed_at,
  changed_by,
  old_data,
  new_data,
  changed_fields
)
SELECT
  e.id,
  1,
  'INSERT',
  coalesce(e.created_at, e.created, timezone('utc', now())),
  coalesce(e.updated_by, e.created_by),
  NULL,
  jsonb_strip_nulls(
    jsonb_build_object(
      'id_property', e.id_property,
      'id_equipamento', e.id_equipamento,
      'codigo', e.codigo,
      'ubicacion', e.ubicacion,
      'detalle_ubicacion', e.detalle_ubicacion,
      'estatus', e.estatus,
      'config', e.config,
      'equipment_detail', e.equipment_detail
    )
  ),
  ARRAY[
    'id_property',
    'id_equipamento',
    'codigo',
    'ubicacion',
    'detalle_ubicacion',
    'estatus',
    'config',
    'equipment_detail'
  ]::text[]
FROM public.equipos e
WHERE NOT EXISTS (
  SELECT 1
  FROM public.equipos_historial h
  WHERE h.equipo_id = e.id
);
